### ISSUE TITLE
fibonacci.s

### ISSUE THREAD

**Issue by tutkudoruk** [bouncmpe/labs344#4]
Hello,
I can not start the first week lab project by writing the first comment.I put the image below.
![20221004_191933](https://user-images.githubusercontent.com/77238738/193872995-ebe967d1-3ff5-452d-bc3d-a2c76cb4bb85.jpg)

**Comment by gokceuludogan** [comment]
Hi, 

It seems that **fibonacci.s** does not exist in that directory. Did you save this file first? 

Please make sure that the file exists by running `ls` command there.

**Comment by tutkudoruk** [comment]
Hi
I thought that You must have saved that file to your lab's docker.What should I do to save this?Where should I save this file?
Best regards

**Comment by gokceuludogan** [comment]
Once you connect to the docker image via VS code,  you can create a new file, copy the content and save it to the default directory which is /home/bouncmpe/. 

You are also free to create directories and save files under those directories. Note that you need to either navigate to the corresponding directory in the terminal or use the full path of the file in that case. More about navigating files & directories: https://datacarpentry.org/shell-genomics/02-the-filesystem/index.html

**Comment by tutkudoruk** [comment]
Is path to directory exactly  /home/bouncmpe/ or longer?I will use cd command and  will try to add the file with copy command.I read from the link also https://www.wikihow.com/Create-and-Delete-Files-and-Directories-from-Windows-Command-Prompt.

**Comment by gokceuludogan** [comment]
It is exactly /home/bouncmpe/. Rather than using terminal commands to add/edit source files, I suggest you to use VS code. Here is the steps you should follow: 
1. Attach to the docker container. This will open a new VS code window which allows you to see and edit files inside the container. 
![image](https://user-images.githubusercontent.com/9639399/193904485-7ae70b8d-730c-4761-9680-9a543086fb4d.png)
2. Click _File>New File_, copy file content, and then, click _File>Save_ and name it as _fibonacci.s_
![image](https://user-images.githubusercontent.com/9639399/193905105-ed76184f-ba33-4e61-b502-bc211738d021.png)
3. Click _Terminal>New Terminal_. Run `ls` to make sure that it is saved properly. Then,  you can use RISC-V toolchain programs to compile and run this file. 
![image](https://user-images.githubusercontent.com/9639399/193905940-3d61cca4-fc61-4479-b11c-e77aba4c406b.png)

**Comment by tutkudoruk** [comment]
I could not understand what you mean by copying file content well.

**Comment by tutkudoruk** [comment]
The one of the problems is I do not to know the type of the file this is important for saving. It is not txt.What should I say?

**Comment by gokceuludogan** [comment]
When you click _File>New File_ (choose Text File), it opens an untitled file where you can write your own code or copy [the provided code](https://github.com/bouncmpe/labs344/blob/main/tutorials/fibonacci/fibonacci.s) and paste it there:
![image](https://user-images.githubusercontent.com/9639399/193917717-fc259b54-5934-4ec5-a7d4-463249bd947d.png)
Next, you can click _File>Save_ and name the file as fibonacci.s as below and press OK:
![image](https://user-images.githubusercontent.com/9639399/193918181-ae8929ed-98d3-4993-be6a-1d5bad984cf1.png)
 Then, you should be able to compile & run it.
